version: "3.8"

# SECURITY NOTES:
# - Never commit .env files with real secrets to Git
# - Change default passwords before deploying
# - Use strong JWT secrets in production

services:
  prometheus:
    # Option 1: Pull from Docker Hub (recommended for users)
    image: ${IMAGE_NAME:-itsashn/prometheus}:${IMAGE_TAG:-latest}

    # Option 2: Build locally (uncomment if you want to build instead of pull)
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     APP_VERSION: ${APP_VERSION:-1.0.0}
    #     BUILD_DATE: ${BUILD_DATE}
    #     VCS_REF: ${VCS_REF}

    container_name: prometheus
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      # Persistent storage for uploaded videos and processed content
      - video-data:/app/public/videos
      - temp-data:/app/temp
      - app-data:/app/data
    environment:
      - NODE_ENV=production
      # Note: APP_VERSION, BUILD_DATE, and VCS_REF are baked into the Docker image at build time
      # Don't override them here - they come from the image's build args
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-changeme123}
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-this}
      - DOCKER_CONTAINER=true
      - IMAGE_NAME=${IMAGE_NAME:-itsashn/prometheus}
    env_file:
      - .env
    networks:
      cloudflareTunnel:
        ipv4_address: 172.18.0.7
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/api/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits (optimized for video streaming)
    deploy:
      resources:
        limits:
          memory: 3G # Increased for video processing
          cpus: "2.0" # More CPU for FFmpeg encoding
        reservations:
          memory: 1G # Higher baseline for video handling
          cpus: "1.0"
    labels:
      - "com.prometheus.description=Self-hosted video streaming platform"
      # Version info is available via the API at /api/version

volumes:
  video-data:
    driver: local
  temp-data:
    driver: local
  app-data:
    driver: local

networks:
  cloudflareTunnel:
    external: true
